/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 4.1d1 */
public interface CompilerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVARIABLEDEFINITION = 1;
  public int JJTFUNCTIONDEFINITION = 2;
  public int JJTPARADEFINITION = 3;
  public int JJTMAINFUNCTION = 4;
  public int JJTPARTPROGRAM = 5;
  public int JJTWORD = 6;
  public int JJTIF_WORD = 7;
  public int JJTFOR_WORD = 8;
  public int JJTEQUALS_WORD = 9;
  public int JJTCHOICE = 10;
  public int JJTEQUALS_WORD2 = 11;
  public int JJTRETURN_WORD = 12;
  public int JJTWRITEWORD = 13;
  public int JJTEXPRESSION = 14;
  public int JJTLOGIC_AND = 15;
  public int JJTEQUALITY = 16;
  public int JJTCOMPARISON = 17;
  public int JJTADD = 18;
  public int JJTTERM = 19;
  public int JJTNOTORNEG = 20;
  public int JJTFACTOR = 21;
  public int JJTDEFINITIONFUNCTION = 22;
  public int JJTLOADVALUE = 23;


  public String[] jjtNodeName = {
    "Start",
    "VariableDefinition",
    "FunctionDefinition",
    "ParaDefinition",
    "MainFunction",
    "PartProgram",
    "Word",
    "If_Word",
    "For_Word",
    "Equals_Word",
    "Choice",
    "Equals_Word2",
    "Return_Word",
    "WriteWord",
    "Expression",
    "logic_and",
    "equality",
    "comparison",
    "add",
    "Term",
    "NotOrNeg",
    "Factor",
    "DefinitionFunction",
    "loadValue",
  };
}
/* JavaCC - OriginalChecksum=978d5c6d4a78863947a9a422c9e3541f (do not edit this line) */
